apiVersion: batch/v1
kind: Job
metadata:
  name: beam-wordcount-py
spec:
  template:
    metadata:
      labels:
        app: beam-wordcount-py
    spec:
      containers:
        - name: beam-wordcount-py
          image: ${IMAGE_URL}
          command: ["python3"]
          args:
            - "-m"
            - "apache_beam.examples.wordcount"
            - "--runner=FlinkRunner"
            - "--flink_master=${JOBMANAGER_ENDPOINT}:8081"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
            - "--requirements_file=/tmp/requirements.txt"
            - "--input"
            - "s3://${S3_BUCKET}/beam/input/shakespeare_kinglear.txt"
            - "--output"
            - "s3://${S3_BUCKET}/beam/output/shakespeare_kinglear_wordcount"
      restartPolicy: Never