apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: default
  name: beam-flink-cluster
spec:
  image: flink:1.14.6
  flinkVersion: v1_14
  serviceAccount: flink
  flinkConfiguration:
    jobmanager.rpc.address: beam-flink-cluster
    taskmanager.numberOfTaskSlots: "2"
    blob.server.port: "6124"
    jobmanager.rpc.port: "6123"
    taskmanager.rpc.port: "6122"
    queryable-state.proxy.ports: "6125"
    jobmanager.memory.process.size: "1600m"
    taskmanager.memory.process.size: "1728m"
    parallelism.default: "2"
  jobManager:
    replicas: 1
  taskManager:
    replicas: 2
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: beam-taskmanager-pod
      spec:
        containers:
          # Beam sidecar container
          - name: beam-worker-pool
            image: apache/beam_python3.9_sdk:2.43.0
            args: ["--worker_pool"]
            ports:
            - containerPort: 50000
              name: pool
            livenessProbe:
              tcpSocket:
                port: 50000
              initialDelaySeconds: 30
              periodSeconds: 60
