apiVersion: batch/v1
kind: Job
metadata:
  name: beam-hello-world
spec:
  template:
    metadata:
      labels:
        app: beam-hello-world
    spec:
      containers:
        - name: beam-hello-world
          image: ${IMAGE_URL}
          command: ["python3"]
          args:
            - "/src/hello_world.py"
            - "--runner=FlinkRunner"
            - "--flink_master=${JOBMANAGER_ENDPOINT}:8081"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
      restartPolicy: Never